# Generated by Django 4.0.5 on 2022-07-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicDeviceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('model_number', models.CharField(default=0, max_length=25)),
                ('serial_number', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=250)),
                ('price', models.FloatField()),
                ('has_warranty', models.BooleanField()),
            ],
        ),
        migrations.AddIndex(
            model_name='electronicdevicedetail',
            index=models.Index(fields=['type', 'brand_name', 'serial_number'], name='device_elec_type_c31d87_idx'),
        ),
    ]
